"""initial_schema

Revision ID: 452c69171ff1
Revises: 
Create Date: 2026-06-17 11:30:58.966310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '452c69171ff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.alter_column('documents', 'company_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='关联股票代码',
               existing_nullable=False)
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='文档类型 report/announcement/transcript',
               existing_nullable=False)
    op.alter_column('documents', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_docs_company'), table_name='documents')
    op.create_index(op.f('ix_documents_company_code'), 'documents', ['company_code'], unique=False)
    op.drop_table_comment(
        'documents',
        existing_comment='文档切片',
        schema=None
    )
    op.alter_column('financial_data', 'company_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('financial_data', 'report_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='报告期',
               existing_nullable=False)
    op.alter_column('financial_data', 'metric_name',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='指标名称',
               existing_nullable=False)
    op.alter_column('financial_data', 'metric_value',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               comment=None,
               existing_comment='指标值',
               existing_nullable=True)
    op.alter_column('financial_data', 'source',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               comment=None,
               existing_comment='数据来源 akshare/tushare/wind',
               existing_server_default=sa.text("'akshare'::character varying"))
    op.alter_column('financial_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_fd_company_date'), table_name='financial_data')
    op.drop_index(op.f('idx_fd_metric'), table_name='financial_data')
    op.create_index(op.f('ix_financial_data_company_code'), 'financial_data', ['company_code'], unique=False)
    op.drop_table_comment(
        'financial_data',
        existing_comment='财务数据中心',
        schema=None
    )
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='进度 0-100',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tasks_company'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_created'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_table_comment(
        'tasks',
        existing_comment='任务记录',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'tasks',
        '任务记录',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_created'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('idx_tasks_company'), 'tasks', ['company_code'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='进度 0-100',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table_comment(
        'financial_data',
        '财务数据中心',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_financial_data_company_code'), table_name='financial_data')
    op.create_index(op.f('idx_fd_metric'), 'financial_data', ['metric_name'], unique=False)
    op.create_index(op.f('idx_fd_company_date'), 'financial_data', ['company_code', 'report_date'], unique=False)
    op.alter_column('financial_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('financial_data', 'source',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               comment='数据来源 akshare/tushare/wind',
               existing_server_default=sa.text("'akshare'::character varying"))
    op.alter_column('financial_data', 'metric_value',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               comment='指标值',
               existing_nullable=True)
    op.alter_column('financial_data', 'metric_name',
               existing_type=sa.VARCHAR(length=64),
               comment='指标名称',
               existing_nullable=False)
    op.alter_column('financial_data', 'report_date',
               existing_type=sa.DATE(),
               comment='报告期',
               existing_nullable=False)
    op.alter_column('financial_data', 'company_code',
               existing_type=sa.VARCHAR(length=10),
               comment='股票代码',
               existing_nullable=False)
    op.create_table_comment(
        'documents',
        '文档切片',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_documents_company_code'), table_name='documents')
    op.create_index(op.f('idx_docs_company'), 'documents', ['company_code', 'doc_type'], unique=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(length=32),
               comment='文档类型 report/announcement/transcript',
               existing_nullable=False)
    op.alter_column('documents', 'company_code',
               existing_type=sa.VARCHAR(length=10),
               comment='关联股票代码',
               existing_nullable=False)
    op.drop_column('documents', 'embedding')
    # ### end Alembic commands ###
